export const courses = [
  {
    id: 1,
    title: 'Build a Full Stack React App',
    description:
      'Learn to create a complete React application with Node.js backend, authentication, and database integration.',
    thumbnail: 'https://img.youtube.com/vi/dQw4w9WgXcQ/maxresdefault.jpg',
    originalVideoUrl: 'https://youtube.com/watch?v=dQw4w9WgXcQ',
    videoTitle: 'React Full Stack Tutorial - 3 Hours Complete Course',
    channel: 'Code with John',
    duration: '3h 24m',
    totalLessons: 24,
    completedLessons: 18,
    status: 'in-progress',
    progress: 75,
    tags: ['React', 'Node.js', 'Full Stack', 'JavaScript'],
    createdAt: new Date('2024-01-15'),
    lastAccessed: new Date('2024-01-20'),
    difficulty: 'intermediate',
  },
  {
    id: 2,
    title: 'Python for Data Science',
    description:
      'Master data analysis, visualization, and machine learning with Python, pandas, and scikit-learn.',
    thumbnail: 'https://img.youtube.com/vi/rfscVS0vtbw/maxresdefault.jpg',
    originalVideoUrl: 'https://youtube.com/watch?v=rfscVS0vtbw',
    videoTitle: 'Complete Python Data Science Course - 4 Hours',
    channel: 'Data Science Pro',
    duration: '4h 12m',
    totalLessons: 32,
    completedLessons: 32,
    status: 'completed',
    progress: 100,
    tags: ['Python', 'Data Science', 'Machine Learning', 'Pandas'],
    createdAt: new Date('2024-01-10'),
    lastAccessed: new Date('2024-01-18'),
    difficulty: 'beginner',
  },
  {
    id: 3,
    title: 'Vue.js 3 Composition API',
    description:
      "Deep dive into Vue 3's Composition API, state management, and modern development patterns.",
    thumbnail: 'https://img.youtube.com/vi/YrxBCBibVo0/maxresdefault.jpg',
    originalVideoUrl: 'https://youtube.com/watch?v=YrxBCBibVo0',
    videoTitle: 'Vue 3 Composition API Complete Guide - 2.5 Hours',
    channel: 'Vue Mastery',
    duration: '2h 48m',
    totalLessons: 16,
    completedLessons: 8,
    status: 'in-progress',
    progress: 50,
    tags: ['Vue.js', 'Composition API', 'JavaScript', 'Frontend'],
    createdAt: new Date('2024-01-18'),
    lastAccessed: new Date('2024-01-22'),
    difficulty: 'intermediate',
  },
  {
    id: 4,
    title: 'Docker & Kubernetes Fundamentals',
    description:
      'Learn containerization with Docker and orchestration with Kubernetes for scalable applications.',
    thumbnail: 'https://img.youtube.com/vi/3c-iBn73dDE/maxresdefault.jpg',
    originalVideoUrl: 'https://youtube.com/watch?v=3c-iBn73dDE',
    videoTitle: 'Docker & Kubernetes Tutorial - 5 Hour Complete Course',
    channel: 'DevOps Academy',
    duration: '5h 16m',
    totalLessons: 28,
    completedLessons: 4,
    status: 'in-progress',
    progress: 14,
    tags: ['Docker', 'Kubernetes', 'DevOps', 'Containers'],
    createdAt: new Date('2024-01-22'),
    lastAccessed: new Date('2024-01-23'),
    difficulty: 'advanced',
  },
  {
    id: 5,
    title: 'JavaScript ES6+ Modern Features',
    description:
      'Master modern JavaScript features including async/await, destructuring, modules, and more.',
    thumbnail: 'https://img.youtube.com/vi/nZ1DMMsyVyI/maxresdefault.jpg',
    originalVideoUrl: 'https://youtube.com/watch?v=nZ1DMMsyVyI',
    videoTitle: 'Modern JavaScript ES6+ Complete Course - 2 Hours',
    channel: 'JavaScript Pro',
    duration: '2h 15m',
    totalLessons: 18,
    completedLessons: 18,
    status: 'completed',
    progress: 100,
    tags: ['JavaScript', 'ES6', 'Modern JS', 'Frontend'],
    createdAt: new Date('2024-01-08'),
    lastAccessed: new Date('2024-01-14'),
    difficulty: 'intermediate',
  },
  {
    id: 6,
    title: 'Next.js 14 App Router',
    description:
      'Build modern web applications with Next.js 14, including server components and the new app router.',
    thumbnail: 'https://img.youtube.com/vi/wm5gMKuwSYk/maxresdefault.jpg',
    originalVideoUrl: 'https://youtube.com/watch?v=wm5gMKuwSYk',
    videoTitle: 'Next.js 14 Complete Tutorial - App Router & Server Components',
    channel: 'Next.js Hub',
    duration: '3h 45m',
    totalLessons: 22,
    completedLessons: 1,
    status: 'in-progress',
    progress: 5,
    tags: ['Next.js', 'React', 'Server Components', 'Full Stack'],
    createdAt: new Date('2024-01-25'),
    lastAccessed: new Date('2024-01-25'),
    difficulty: 'intermediate',
  },
]
